export const TestError = () => {
  throw new Error("Тестовая ошибка");
};
